export class PartnersBox{
  constructor(){
    this.people = [
      { name: 'Lorem, ipsum.', image: 'https://picsum.photos/200/300/?random', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam, quia magnam perferendis dolores nesciunt exercitationem nostrum sit ut aspernatur maxime repellat distinctio! Ad assumenda atque vero magni ducimus voluptas nemo, amet voluptatibus a voluptates earum provident. Assumenda dolorem, excepturi repellat maxime at dolorum recusandae ea qui reiciendis ab ratione? Nisi architecto itaque, repellat dolore eos recusandae aliquid, quidem quae unde facilis temporibus eaque libero debitis ad eum tempore distinctio asperiores odit laboriosam deserunt impedit ab! Sunt, repudiandae minima omnis exercitationem repellendus unde odio fuga sit consequatur neque optio enim harum similique! At sit fugiat, possimus ipsam quia ducimus doloremque deleniti.'},
      { name: 'Lorem, ipsum.', image: 'https://picsum.photos/200/300/?random', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam, quia magnam perferendis dolores nesciunt exercitationem nostrum sit ut aspernatur maxime repellat distinctio! Ad assumenda atque vero magni ducimus voluptas nemo, amet voluptatibus a voluptates earum provident. Assumenda dolorem, excepturi repellat maxime at dolorum recusandae ea qui reiciendis ab ratione? Nisi architecto itaque, repellat dolore eos recusandae aliquid, quidem quae unde facilis temporibus eaque libero debitis ad eum tempore distinctio asperiores odit laboriosam deserunt impedit ab! Sunt, repudiandae minima omnis exercitationem repellendus unde odio fuga sit consequatur neque optio enim harum similique! At sit fugiat, possimus ipsam quia ducimus doloremque deleniti.'},
      { name: 'Lorem, ipsum.', image: 'https://picsum.photos/200/300/?random', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam, quia magnam perferendis dolores nesciunt exercitationem nostrum sit ut aspernatur maxime repellat distinctio! Ad assumenda atque vero magni ducimus voluptas nemo, amet voluptatibus a voluptates earum provident. Assumenda dolorem, excepturi repellat maxime at dolorum recusandae ea qui reiciendis ab ratione? Nisi architecto itaque, repellat dolore eos recusandae aliquid, quidem quae unde facilis temporibus eaque libero debitis ad eum tempore distinctio asperiores odit laboriosam deserunt impedit ab! Sunt, repudiandae minima omnis exercitationem repellendus unde odio fuga sit consequatur neque optio enim harum similique! At sit fugiat, possimus ipsam quia ducimus doloremque deleniti.'}
    ]
  }
}

